Unity-Developer-Community/UDC-Bot

- DiscordBot/Modules/UserModule.cs
- Removes inline which causes format issues when title is really long.
- "Read More.." instead of just "More" which may be a bit subjective.
Just a problem with how I was using inlines, any long titles would introduce weird formatting since the inline elements can't really align the way I was trying to use them.
> Fixes formatting of the returned results

- DiscordBot/Modules/UserModule.cs
This fixes #67 by using regex to detect when a embed link is within a quoted message and adding a slash `\` in front to escape it.
**Test message I used:**
<pre>
Quote test:
```cs
public string text = null;
```
[Google](https://bing.com/)
**Bold**
*Italicized*
~~***Bold Italicized Strikethrough***~~
`inline code`
> Quote: This was written by someone else
> Multiline Quote!
> They also had a link! Wow! [Unity](https://www.unrealengine.com/marketplace/en-US/store?randomQueryString=asdfaosuhuoiahotrh984t398t)
||Uh oh. Spoilers!||
Whoa another link: [Bing](https://google.com/)
Image attached below:
</pre>
**Before the change:**
**After the change:**
> Replace embed links in quoted messages with escaped versions (Issue #67)

- DiscordBot/Extensions/DateExtensions.cs
- DiscordBot/Modules/UserModule.cs
Discord formatted Timestamp.
- Added an extension to get a Unix timestamp from a datetime.
- Remove the :stuck_out_tongue_winking_eye: the bot would do if it couldn't find a users birthday.
> Replace date string with UnixTimeStamp

- DiscordBot/Modules/UserModule.cs
- Will respond with a small embed informing user if the API doesn't respond. Instead of the old behaviour of silently dying.
- Replaced the ``or I can't understand them`` in favor of ``or incorrectly used`` to reduce the humanization of machines. :kappa:
The embed is deleted after 10 seconds.
> Improve !curr

- DiscordBot/Modules/UserModule.cs
- Fix where it only compares if fromRate is -1 twice instead of also checking toRate. (whoops)
This resulted in command of !curr 1 aud usd.
to return negative values since usd doesn't exist and would use value of -1 as ``USD.`` value. Now it will just tell the user that ``USD.`` doesn't exist.
> Fix bug where only compares fail fromRate

- DiscordBot/Services/UserService.cs
- DiscordBot/Settings/Deserialized/Settings.cs
- DiscordBot/Settings/Settings.example.json
Now will only scold users every X minutes. Default config setup, every 6 hours.
There is no cleanup, but the tiny data held by this dictionary is trivial on our scale.
Resolves #106
> Don't re-scold for everyone

- DiscordBot/Services/UpdateService.cs
``displaystyle`` is in all broken embeds due to additional formatting involved. To get around this, we check the extract for ``displaystyle`` if it is found, we do an excessive sanitize of white space and new lines.
This will make results a block of text and destroy natural paragraphs if any exist. But only for results where this is ran.
Resolves #108
> Fix !wiki large broken embeds

- DiscordBot/Modules/TicketModule.cs
- DiscordBot/Modules/UserModule.cs
- DiscordBot/Preconditions.cs
- DiscordBot/Services/UserService.cs
- DiscordBot/Settings/Deserialized/Settings.cs
Fix #117
- Bot auto create threads after message in certain channels.
- List of channels are configurable in config.
- Thread name will be `[Title] - [UserName]` where `[Title]` is from the config.
- It will ignore messages written by bots
- It will ignore messages that start with some prefixes (like `!` or `w!`). In config.
> Bot auto create threads after message in certain channels

- DiscordBot/Services/ReminderService.cs
- If only 1 reminder was set, when it fires there will be 0, and `_reminders.Min`` will throw an exception. Whoops.
> Fix Exception

- DiscordBot/Modules/ReminderModule.cs
Negative time is impossible due to the regex, I fixed this early and forgot to improve the error message for failed dates.
it will now respond with the correct syntax for incorrect times.
> Fix confusing message for negative time

- DiscordBot/Modules/UserModule.cs
Returns date/days without the UTC since that is confusing people. 
It is a shame timestamp doesn't have similar tag just for days until date.
> Return birthday to using a plain date string

- DiscordBot/Modules/UserSlashModule.cs
- DiscordBot/Settings/Deserialized/Settings.cs
- DiscordBot/Settings/Settings.example.json
Users can now right click on a message or click the `...` which will have a "Report Message" button, the reported message content/author/attachments are posted into bot-commands.
Note: 
Obviously posting this in bot-commands isn't appropriate as it'll be lost to spam, do we want a new channel? or post it into one of the other moderator channels? If so, which?
Behaviour:
- Can't report self, bot or webhooks
A context message is also sent as response to confirm the message was reported.
> Feature - ContextMenu Report message

- DiscordBot/Modules/UserModule.cs
- DiscordBot/Services/CurrencyService.cs
Results are now caches a bit better, if API is down if we have previously get the data, we will still use it, but a stale tag is included with the response.
Valid currencies are fetched the first time the bot tries to access the API, and builds a dictionary. This dictionary is used for all future requests and will be much faster at notifying the user of incorrect currencies.
API results are cached for 6 hours instead of 24, after 6 hours the next time the currency is used it tries to add new data.
> [Improvement] Currency command caching

- DiscordBot/Modules/ReminderModule.cs
- DiscordBot/Services/ReminderService.cs
Once a user uses `!remindme 5months whatever` the bot uses a configured emote to indicate that it is live. If other users use the same reaction, they will be pinged in the message when the reminder triggers.
This might be useful for people who want to organize an event together, or be reminded of a certain thing. The piggy-back reminder does not consume one of the users reminders as the reaction is checked when the reminder is due. If a user removes their reaction, they will no longer be reminded once the reminder is fired.
A max limit of 10 users will be reminded (+1 for author)
This will also work retrospectively, but messages without the reaction won't get the additional pings. (The emote was only added the other week/month?)
> [Improvement] Multi-User reminders

- DiscordBot/Modules/WeatherModule.cs
Hi there!
I'm Pawan Kartik and I work at DeepSource. Our internal logs indicated that the Autofix generated for this particular line in the pull request https://github.com/Unity-Developer-Community/UDC-Bot/pull/217 might not be accurate.
Actual line from the source:
```csharp
if (res != null) return true;
```
Autofix generated:
```csharp
if (object.Equals(res, default(T))) return true;
```
Ideal code that should've been generated:
```csharp
if (!object.Equals(res, default(T))) return true;
```
This PR fixes the incorrect code that was generated. Additionally, we've staged a fix internally that should roll out globally in a couple of hours.
We sincerely regret the inconvenience caused.
> Fix incorrect object comparison

- DiscordBot/Extensions/ContextExtension.cs
- DiscordBot/Extensions/MessageExtensions.cs
- DiscordBot/Modules/UserModule.cs
- DiscordBot/Services/CurrencyService.cs
Replaces the old API with something not bad.
Key changes:
- `!currname` 
- `!curr` will default to USD if no to currency provided
- API is no longer garbage
- Added extension for Context and Messages to allow a single call to check if any Mentions/Roles/Everyone is in context to avoid dangerous replies. (Allows bot to quickly check context and just ignore a comand if it has mentions)
> Fix - Replace dead Currency API

- DiscordBot/Extensions/UserDBRepository.cs
- DiscordBot/Services/DatabaseService.cs
I think the lib we're using expects non-async calls to be closed externally, how I've setup the test to run now is a bit eh, and may result in a race condition in the future if more complicated database stuff is added on first boot, but unsure.
How it is now does appear to close everything, so I'm unsure if we'll still run into issues with !profile or !top time will tell though.
> Fix - Convert initial DB Test to be async

- DiscordBot/DiscordBot.csproj
- DiscordBot/Extensions/ChannelExtensions.cs
- DiscordBot/Extensions/StringExtensions.cs
- DiscordBot/Extensions/UserExtensions.cs
- DiscordBot/Modules/UnityHelp/UnityHelpInteractiveModule.cs
- DiscordBot/Modules/UnityHelp/UnityHelpModule.cs
- DiscordBot/Program.cs
- DiscordBot/Services/FeedService.cs
- DiscordBot/Services/LoggingService.cs
- DiscordBot/Services/UnityHelp/Components/HelpBotMessage.cs
- DiscordBot/Services/UnityHelp/Components/ThreadContainer.cs
- DiscordBot/Services/UnityHelp/UnityHelpService.cs
- DiscordBot/Services/UnityHelpService.cs
- DiscordBot/Settings/Deserialized/Settings.cs
- DiscordBot/Utils/Utils.cs
General purpose PR that is a little overscoped but encapsulates most of the required needs of a few forum related issues we currently have.
- Moves all RSS into Unity-News (ID Variable which must be forum) and posts the feeds as forum/threads in that channel with the included tags and mention roles related.
**Why**:  News is simple, it is more organized and digestable, as for the Beta/New releases, these are already ignored by 99% of people in the unity-discussion channel, at least now they'll be grouped into a place that if people do want to talk they can. The roles related will still be pinged.
- When a question is started, it checks if any tags are included and asks the user to add some. (This message is deleted once a tag is added)
- When a question is started, if it is shorter than …
> Feature - Forum Improvements & Help Service

- DiscordBot/Services/FeedService.cs
Not sure what the feed.id is meant to be doing, it looks like it is trying to do the same but we still have duplicate posts. But the service handling this as well should help prevent duplicates further.
> Fix: Prevent duplicate unity version feed

- DiscordBot/Extensions/UserExtensions.cs
- DiscordBot/Modules/ModerationModule.cs
- DiscordBot/Modules/UserModule.cs
- DiscordBot/Modules/UserSlashModule.cs
- DiscordBot/Program.cs
- DiscordBot/Services/DatabaseService.cs
- DiscordBot/Services/LoggingService.cs
- DiscordBot/Services/ModerationService.cs
- DiscordBot/Services/ReactRoleService.cs
- DiscordBot/Services/Recruitment/RecruitService.cs
- DiscordBot/Services/UnityHelp/UnityHelpService.cs
- DiscordBot/Services/UserService.cs
- DiscordBot/Settings/Deserialized/Settings.cs
- DiscordBot/Settings/Settings.example.json
- DiscordBot/Utils/StringUtil.cs
- README.md
Fairly basic clean-up of the repo, a number of simple fixes have been applied.
- Added some additional information to the ReadMe regarding Docker and getting the project to run, and remove other misc details that had long since been abandoned.
- Replaced use of Discriminator with DisplayName "NickName (aka Username)" where possible, otherwise use of DisplayName (which will show NickName as preference, with Username shown if no Nick)
- Added some additional checks during database startup to prevent some issues with docker
- Track Deleted and Edited messages better, smaller format, include edited messages if still exists in cached results, but also includes a small message any time a message is edited to maintain proof of change if required.
- Introduced a Bool in the settings to easily …
> Feat: Misc Fixes & Recruitment Channel BabySitter

- DiscordBot/Extensions/UserExtensions.cs
- DiscordBot/Program.cs
- DiscordBot/Services/FeedService.cs
- DiscordBot/Services/Recruitment/RecruitService.cs
- DiscordBot/Services/ReminderService.cs
- DiscordBot/Utils/StringUtil.cs
Continued clean-up, and fix a couple small issues introduced by recuirtment service.
- Fix issue with Recruitment ignoring any tags, not just ones we want
- Fix issue with rolegroup identifier not returning correct result
- Fix bug introduced from deprecated xml reader
- Impr: RecruitService locks a channel after the edit period has passed
- Impr: Increase max reminders to 10 for the crazy people
- Impr: RecruitmentService will delete any messages by non-mods in recruitment channels to prevent cross-post while editing is active.
#212
> Feat: Misc Fixes & Recruitment Service

- DiscordBot/Modules/TipModule.cs
- DiscordBot/Program.cs
- DiscordBot/Services/Tips/Components/Tip.cs
- DiscordBot/Services/Tips/TipService.cs
- DiscordBot/Settings/Deserialized/Settings.cs
Isolate SimplyJPK's Tip Service from his feat/misc-improvements branch.
> Isolate SimplyJPK's Tip Service from his feat/misc-improvements branch

- DiscordBot/Services/Moderation/IntroductionWatcherService.cs
Moderators can post multiple messages, users cannot
> Immunize Mods in IntroductionWatcherService.cs

- DiscordBot/Extensions/StringExtensions.cs
- DiscordBot/Extensions/UserExtensions.cs
- DiscordBot/Modules/UserModule.cs
- DiscordBot/Services/UnityHelp/UnityHelpService.cs
- DiscordBot/Settings/Deserialized/Settings.cs
Adding a couple extension methods to make writing lists of things/users/names easier.
> User string and list extensions for convenience and consistency

- DiscordBot/Extensions/StringExtensions.cs
- DiscordBot/Modules/ModerationModule.cs
- DiscordBot/Services/UserService.cs
- DiscordBot/Settings/Deserialized/Settings.cs
- DiscordBot/Utils/WebUtil.cs
Found a couple small exploits/edgecases and overly complex code in the Thanks patterns and Karma credit code.  Also using some of the previously added phrase-list grammar extensions.
> Refactor Karma and Thanks to simplify and avoid exploits

- DiscordBot/Services/PublisherService.cs
Potential alternative to Issue 58
https://github.com/Unity-Developer-Community/UDC-Bot/issues/58
We have a lot of existing @Publishers with no database to associate them with the packageID they published.
Instead of relying on a database of publisher/package IDs, we offer an improved publisher validation email that explains how a real publisher can fight back against spam (if it's happening).
> Better publisher validation email PublisherService.cs

- DiscordBot/Modules/UserSlashModule.cs
Power to the People!  Down with "divine power" of Kings!
> Vive la Révolution et à bas « Dieu et mon droit »!
