DiscordBot/DiscordBot.csproj, DiscordBot/Modules/ModerationModule.cs, DiscordBot/Modules/TicketModule.cs, DiscordBot/Modules/UserModule.cs
Remake of https://github.com/Sirush/UDHBot/pull/116
=> Reply karma

DiscordBot/Program.cs
=> Sends a message to BotAnnouncements when Started/Ready

DiscordBot/Services/UserService.cs
generates folder on start if doesn't exist prior.
fixes #36
=> Fix problem missing directory for UserService ProfileCards

DiscordBot/Services/UserService.cs
=> Fix swapped karma and level rank on profile card

DiscordBot/Services/UserService.cs, DiscordBot/Settings/Deserialized/Settings.cs
- Reduces spam of bot raids
- Sends formatted welcome first thing
- Runs the method in new Task to avoid gateway lock.
- Checks if moderation is currently enabled and ignores checking mutedUsers if disabled.
resolves #60
=> Will welcome a user after a defined amount of time

DiscordBot/Modules/UserModule.cs
This fixes issue #65.
This changes the rank embed to have a field per user rather than 3 inline fields acting as columns.
On mobile, the columns were wrapping and being displayed vertically, making the embed hard to read.
The issue of "Invalid User" mentions is also fixed by having the bot retrieve the username.
(This was actually required since user mentions don't work at all when they are in the field name.)
Take a look at the issue's comments to see how it looks before and after.
=> Change how the rank embed is displayed (Issue #65)

DiscordBot/Services/UserService.cs
- More design resources
- Removed brackey, replaced with official unity for Introductory tutorials
- Added "When asking questions, remember to ask your question, [don't ask to ask](https://dontasktoask.com/)" to the first paragraph of welcome
=> Improve FormattedWelcome

DiscordBot/Extensions/UserDBRepository.cs, DiscordBot/Modules/UserModule.cs, DiscordBot/Services/DatabaseService.cs, DiscordBot/Services/UserService.cs
=> Added columns and commands for weekly, monthly and yearly karma

DiscordBot/Modules/TimeModule.cs, DiscordBot/Settings/Deserialized/Settings.cs
=> Added time command

DiscordBot/DiscordBot.csproj, DiscordBot/Modules/ModerationModule.cs, DiscordBot/Modules/UserModule.cs, DiscordBot/Program.cs, DiscordBot/Services/ModerationService.cs, DiscordBot/Services/ReactRoleService.cs, DiscordBot/Services/UserService.cs
=> Changed Discord.Net to Discord.Net.Labs.

DiscordBot/Services/FeedService.cs
=> Bot now start thread after Unity blog news

DiscordBot/Services/CommandHandlingService.cs
Bot won't respond to someone just typing ``!`` in chat
=> Fix ! firing "Unknown command."

DiscordBot/Services/CommandHandlingService.cs
``!? !?!? !?!!!``
``!!!!!?``
``!?``
Will no longer inform the user their anger is not a command
=> Ignore collections of "!? "

DiscordBot/Modules/ReminderModule.cs, DiscordBot/Services/ReminderService.cs
- Logs exceptions during update.
- Can be rebooted if crashed
- Wrapped CheckReminders in an Try Catch to announce problems faster
- Re-ordered some of the methods in the classes to make ownership more obvious.
=> Additional error checking

DiscordBot/Services/ReminderService.cs
- Fix LogAction Typo
- Additional logging when the service is starting
=> Fix Typo, Additional logging

DiscordBot/Services/UserService.cs
When a user joins they're still added to a cooldown for welcome, but if they manage to send a message before the 'cooldown' has ended, the bot will welcome them immediately.
This should hopefully reduce the times where someone will have spoken a few lines in offtopic, and then they get the awkward welcome after people are already interacting with them.
=> Small Welcome Service inside the UserService

DiscordBot/Modules/UserModule.cs
=> Additional logging for Profile and Top

DiscordBot/Modules/ModerationModule.cs, DiscordBot/Modules/ReactionRoleModule.cs, DiscordBot/Modules/ReminderModule.cs, DiscordBot/Modules/TicketModule.cs, DiscordBot/Modules/TimeModule.cs, DiscordBot/Modules/UserModule.cs, DiscordBot/Modules/WeatherModule.cs, DiscordBot/Services/CommandHandlingService.cs
Modules now work more like they're meant to, removed constructors and replaced with the intended depency injected properties suggested by documentation.
I've also improved the CommandHandlingService to cache results for ``!help``, this alone should be a big improvement in performance as any module using the old help command basically had their helplist constructed every time a command was used, even if it wasn't help, which is obviously stupid.
=> Improvements/Dependency Injection

DiscordBot/Services/ReminderService.cs
- Resolves index error which sometimes made some reminders to posted twice, sometimes to someone else if next reminder we close.
- Cleaned up indentation to improve clarity of method and what it is doing.
=> Fix error, and improve indentation (remind-me)

DiscordBot/Modules/ModerationModule.cs, DiscordBot/Modules/UserSlashModule.cs, DiscordBot/Program.cs, DiscordBot/Services/CommandHandlingService.cs, DiscordBot/Services/UserService.cs
Once #165 is merged, this is safe to be merge, integrates slash commands into the command handler servics. Adds a couple simple slash commands as well from the UserModule/Service
=> Slash command integration

DiscordBot/Modules/ModerationModule.cs, DiscordBot/Services/DatabaseService.cs
Two small changes
- Bot will start and run even if database connection fails on startup instead of failing to create commands and such.
- ModerationService should now instance correctly? which will fix the bot-announcement messages not showing deleted messages.
=> Fix/bot reliability (Deleted Messages, Database Connection Failure)

DiscordBot/Modules/WeatherModule.cs
=> Min/Max temps was useless, adds Wind direction, Rain/Snow for last hour (if any) and sunrise/sunset

DiscordBot/Modules/AirportModule.cs, DiscordBot/Modules/WeatherModule.cs, DiscordBot/Program.cs, DiscordBot/Services/AirportService.cs, DiscordBot/Services/WeatherService.cs, DiscordBot/Settings/Deserialized/Settings.cs, DiscordBot/Settings/Settings.example.json, DiscordBot/Utils/SerializeUtil.cs
Integrates 2 API which allows the use of searching for a flight ticket from City A to City B, there is no customization as that would cause users to use it more. It is more just a fun command to joke about moving, similar to how people complain about weather. A conversation starter if anything.
> Restricted use: Can only be called in off-topic or bot-commands
Use:
`!flight "Sydney" "Paris"`
Result:
Additional details about flight have been commented out as the embed was getting quite bulky for a "fun" command.
Also Added:
- Groups settings by region for readability
- Makes a WeatherService which has 2 commonly used calls (This is because WeatherAPI has very loose rate limits, and utilized by the AirportService)
- Fixed a typo in WeatherContainer
=> Feature - Flights

DiscordBot/Modules/WeatherModule.cs
Few small changes:
- More contrast to colour in embeds for temperature
- <= -10c range, which is a dark blue since people live in places crazy enough to get so cold
- Time included with title of embed as it has been requested a couple times, mostly by steve
=> [Improvement] Weather Module visible information

DiscordBot/Modules/ReminderModule.cs, DiscordBot/Modules/UserModule.cs, DiscordBot/Modules/UserSlashModule.cs, DiscordBot/Modules/WeatherModule.cs, DiscordBot/Services/CurrencyService.cs, DiscordBot/Services/ReminderService.cs
- https://github.com/Unity-Developer-Community/UDC-Bot/pull/208 
- https://github.com/Unity-Developer-Community/UDC-Bot/pull/206 
- https://github.com/Unity-Developer-Community/UDC-Bot/pull/205
=> Release 1.5.6

DiscordBot/Modules/UserModule.cs
Adds a return statement where one was missing
=> Fix - New Currency, missing handler for missing currency

DiscordBot/Modules/UserModule.cs, DiscordBot/Services/UserService.cs
Nothing exciting,
- slight optimization for a couple messages
- welcome the user on MessageRecieved as well as "OnTyping" to avoid speedy users who can type faster than lightning and get a message sent before discord can smell 'em.
- Ignores "Levelup" messages until level 4 so users have a bit more time to learn they exist naturally without getting a "congrats" on their 2nd message and asking "wth".
- Removed activity containing Unity adding additional 25% xp (unfair as a lot of people will use plugin for rider/visualstudio to push programming feeds instead of Unity)
- Additional logging around !top and !profile, !profile has more chance to escape early and waits a bit longer for certain things. On failure the log should be more readable. It appears to be a database issue, but I'm unsure …
=> Feature - User Improvements (Logging and misc improvements)

DiscordBot/Settings/UserSettings.json
=> add romanian version of thanks

DiscordBot/Modules/UnityHelp/UnityHelpInteractiveModule.cs, DiscordBot/Modules/UnityHelp/UnityHelpModule.cs, DiscordBot/Modules/UserModule.cs, DiscordBot/Program.cs, DiscordBot/Services/LoggingService.cs, DiscordBot/Services/ReactRoleService.cs, DiscordBot/Services/Recruitment/RecruitService.cs, DiscordBot/Services/UnityHelp/UnityHelpService.cs, DiscordBot/Settings/Deserialized/Settings.cs
=> Feat - More misc fixes, improvements to api/doc

DiscordBot/Services/UserService.cs
Many of the karma messages were using non-preferred usernames.
A couple minor formatting changes mixed in.
=> Karma messages have minor formatting changes and use GetUserPreferredName()

DiscordBot/DiscordBot.csproj, DiscordBot/Extensions/ContextExtension.cs, DiscordBot/Extensions/DBConnectionExtension.cs, DiscordBot/Extensions/EmbedBuilderExtension.cs, DiscordBot/Extensions/UserDBRepository.cs, DiscordBot/Modules/AirportModule.cs, DiscordBot/Modules/ModerationModule.cs, DiscordBot/Modules/ReactionRoleModule.cs, DiscordBot/Modules/UserModule.cs, DiscordBot/Modules/UserSlashModule.cs, DiscordBot/Modules/Weather/WeatherContainers.cs, DiscordBot/Modules/Weather/WeatherModule.cs, DiscordBot/Program.cs, DiscordBot/Services/CommandHandlingService.cs, DiscordBot/Services/CurrencyService.cs, DiscordBot/Services/DatabaseService.cs, DiscordBot/Services/FeedService.cs, DiscordBot/Services/LoggingService.cs, DiscordBot/Services/ModerationService.cs, DiscordBot/Services/ReactRoleService.cs, DiscordBot/Services/ReminderService.cs, DiscordBot/Services/UserExtendedService.cs, DiscordBot/Services/UserService.cs, DiscordBot/Services/WeatherService.cs, DiscordBot/Utils/StringUtil.cs, DiscordBot/Utils/WebUtil.cs
Pretty messy pull request as it covers a few different generalized things
Features:
- Beta/Release feeds include summary updates and Release notes pulled from source (Fragile, but Unity hasn't updated these page formats in years)
- Context extensions to better determine is a message is a Reply, if a reply mentions other people (other than author), or has everyone mentions.
- `!curr` will work in a reply now if no other mention other than author
- `WebUtil` to fetch url content, has XML sanitizer and Deserializer.
- Currency and Feed Services use WebUtil
- Increase message cache to 1024 per channel from 200 to better track message history (May affect memory size, footprint seems quite small though)
- Update LoggingService to be more robust with Flag Enum to log to File/Channel & Console at …
=> Feature: General Improvements

DiscordBot/Attributes/BotCommandChannelAttribute.cs, DiscordBot/Attributes/IgnoreBotsAttribute.cs, DiscordBot/Attributes/RoleAttributes.cs, DiscordBot/Attributes/ThreadAttributes.cs, DiscordBot/Extensions/EmbedBuilderExtension.cs, DiscordBot/Extensions/UserExtensions.cs, DiscordBot/Modules/EmbedModule.cs, DiscordBot/Modules/TicketModule.cs, DiscordBot/Modules/UnityHelp/UnityHelpModule.cs, DiscordBot/Modules/UserModule.cs, DiscordBot/Modules/Weather/WeatherModule.cs, DiscordBot/Program.cs, DiscordBot/Services/CommandHandlingService.cs, DiscordBot/Services/Moderation/IntroductionWatcherService.cs, DiscordBot/Services/ModerationService.cs, DiscordBot/Services/ReminderService.cs, DiscordBot/Services/UnityHelp/UnityHelpService.cs, DiscordBot/Services/UpdateService.cs, DiscordBot/Services/UserService.cs, DiscordBot/Settings/Deserialized/Settings.cs, DiscordBot/Settings/Settings.example.json
Resolves a handful of small issues from the last PR.
Don't merge this until we can confirm other bugs don't exist with babysitters as none of the fixed issues are significant.
- Significant fix for welcome messages for bug that was introduced when race condition was removed. Whoops.
=> Feature: More misc fixes

DiscordBot/Attributes/IgnoreBotsAttribute.cs, DiscordBot/Extensions/MessageExtensions.cs, DiscordBot/Extensions/UserDBRepository.cs, DiscordBot/Modules/UnityHelp/CannedInteractiveModule.cs, DiscordBot/Modules/UnityHelp/CannedResponseModule.cs, DiscordBot/Modules/UnityHelp/GeneralHelpModule.cs, DiscordBot/Modules/UserModule.cs, DiscordBot/Program.cs, DiscordBot/Services/CommandHandlingService.cs, DiscordBot/Services/DatabaseService.cs, DiscordBot/Services/LoggingService.cs, DiscordBot/Services/ModerationService.cs, DiscordBot/Services/UnityHelp/CannedResponseService.cs, DiscordBot/Settings/Deserialized/Settings.cs, DiscordBot/Utils/WebUtil.cs
Just more misc changes, added a bunch of slash command for FAQ-type responses that users can use for help or in response to other peoples questions as "easy answers"
There is a number of quick responses
- HowToAsk
- Paste
- NoCode
- XYProblem
- DeltaTime
- Debugging
- FolderStructure
- GameTooBig
- HowToGoogle
And a couple resource commands, also added a D20 and Roll command for memes. Also added
Added a MemeChannel to settings, and a config to enable/disable a basic meme channel watcher, all it does is look for any discord.gg invites and deletes them immediately as it appears to be the most targeted channel.
- There still appears to be some database error from time to time, but haven't worked out what is directly causing the problem.
=> Feature: Even more misc

DiscordBot/Extensions/UserExtensions.cs, DiscordBot/Modules/ModerationModule.cs, DiscordBot/Services/AirportService.cs, DiscordBot/Services/CommandHandlingService.cs, DiscordBot/Services/DatabaseService.cs, DiscordBot/Services/LoggingService.cs, DiscordBot/Services/ModerationService.cs, DiscordBot/Services/ReminderService.cs, DiscordBot/Services/UserService.cs, DiscordBot/Services/WeatherService.cs, DiscordBot/Settings/Deserialized/Settings.cs
Some more misc cleanup and trying to fix the sql error, I think I've got it this time, sorta. Any time Query() is used from DB Service, it creates a new connection.
This isn't technically the best way to do this, but should prevent the issue from building up and just knocking everything offline at once.
Also added logs for text commands, improve logger status during startup to mention missing keys, etc.
=> Feature: Cleanup, misc improvements, Fix SQL Bug

DiscordBot/Modules/UserModule.cs
Grammar and preferred username changes in messages from UserModule commands.
=> Additional changes to UserModule messages

DiscordBot/Modules/Weather/WeatherModule.cs
Add AM/PM indicator to !time, and use preferred usernames.
=> WeatherModule message changes

DiscordBot/Modules/TipModule.cs
Experimentally allow users with the TipUserRoleId (e.g., Helpers) to use the !tip and !listtips commands.
=> Allow Helpers to !tip in TipModule.cs
